### ISSUE TITLE
any update?

### ISSUE THREAD

**Issue by monomycelium** [pepijndevos/devOS#1]
I was just pondering about how EV3 Classroom sucks and ev3dev is too bloated. Why can't there be an Arduino-like way of programming for embedded? And then, I stumbled upon this, which seemed too good to be true. And it turned out to be so, with the last commit from seven years ago!

@pepijndevos has there been any recent work on this? I would really like to code bare-metal for EV3 just like when I code for Arduino.

**Comment by pepijndevos** [comment]
Not really. You can basically use it as an example of how to run bare metal code, but I have not implemented any APIs.

I did recently do some explorations of bare metal code on the Prime hub, which is an stm32. It would be relatively straightforward to run PyBrick without MicroPython to reuse their API as a bare metal stack.

For my particular use case it was more practical to load native code as a micropython extension

http://pepijndevos.nl/2023/02/25/running-julia-on-the-lego-robot-inventor-hub.html

**Comment by monomycelium** [comment]
I happened to find this repository that seems to get an embedded `ev3` crate working bare-metal. Anyway, I happened to get stuck when my robot would not run to relative position, so I fell back to block coding because of a competition on Friday. However, I hope to come back to coding EV3 projects in Rust.
